### ISSUE TITLE
create client with transport option `agent` leads to ERR_INVALID_PROTOCOL on data write

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-js#186]
### Specifications

* Client Version: 0.4.0
* InfluxDB Version: IOX 
* Platform: AWS

### Code sample to reproduce problem

```typescript
...
        let samples: Sample[] = genGenericSamples("delvaux", 10);
        let points: Point[] = [];

        samples.forEach((sample, index) => {
            points[index] = sampleToPoint(sample)
        })

        const keepAliveAgent = new http.Agent({ keepAlive: true, keepAliveMsecs: 20 * 1000, scheduling: "fifo" });

        const client = new InfluxDBClient({host: props.hostname,
            token: props.token,
            database: props.database,
            // N.B. options port, hostname and protocol are overwritten thus ignored
            // NodeHttpTransport.ts:70-72 in influxdb3.js
            // host is aliased by hostname and seems to also be ignored
            transportOptions: {
               agent: keepAliveAgent,
//               agent: false,
//               host: 'us-east-1-1.aws.cloud2.influxdata.com',
//                host: '192.168.88.71',
               localPort: 32769,
               timeout: 10000,
               foo: "bar"
            }
        })

        await client.write(points)
...
```

### Expected behavior

Expected to be able to connect and write data.  BTW `hostname` from `props` is `https://us-east-1-1.aws.cloud2.influxdata.com`

In general I'm testing possible configuration properties for the client.  This case in a way replicates the connection reuse use-case already addressed in the influxdb2 client. ( https://github.com/influxdata/influxdb-client-js/issues/393#issuecomment-985272866 ).

### Actual behavior

Throws exception 

```
TypeError [ERR_INVALID_PROTOCOL]: Protocol "https:" not supported. Expected "http:"
    at new NodeError (node:internal/errors:387:5)
    at new ClientRequest (node:_http_client:177:11)
    at Be.request [as _requestApi] (node:https:357:10)
    at Be._request (node_modules/@influxdata/influxdb3-client/src/impl/node/NodeHttpTransport.ts:379:22)
    at resolve (node_modules/@influxdata/influxdb3-client/src/impl/node/NodeHttpTransport.ts:142:14)
    at Gzip.cb (node_modules/@influxdata/influxdb3-client/src/impl/node/NodeHttpTransport.ts:305:9)
    at Gzip.zlibBufferOnEnd (node:zlib:161:10)
    at Gzip.emit (node:events:513:28)
    at Gzip.emit (node:domain:489:12)
    at endReadableNT (node:internal/streams/readable:1358:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```

**Comment by bednar** [comment]
@karel-rehor, try to import `Agent` from `https` package: `const keepAliveAgent = new https.Agent({ keepAlive: true, keepAliveMsecs: 20 * 1000, scheduling: "fifo" });`

This works for me:

```typescript
import {InfluxDBClient, Point} from '@influxdata/influxdb3-client'
import * as https from 'https'

type Defined<T> = Exclude<T, undefined>

/* allows to throw error as expression */
const throwReturn = <T>(err: Error): Defined<T> => {
  throw err
}

/* get environment value or throw error if missing */
const getEnv = (variableName: string): string =>
  process.env[variableName] ??
  throwReturn(new Error(`missing ${variableName} environment variable`))

/* eslint-disable no-console */
async function main() {
  // Use environment variables to initialize client
  const host = getEnv('INFLUX_HOST')
  const token = getEnv('INFLUX_TOKEN')
  const database = getEnv('INFLUX_DATABASE')

  const keepAliveAgent = new https.Agent({
    keepAlive: true,
    keepAliveMsecs: 20 * 1000,
    scheduling: 'fifo',
  })

  // Create a new client using an InfluxDB server base URL and an authentication token
  const client = new InfluxDBClient({
    host,
    token,
    transportOptions: {agent: keepAliveAgent},
  })

  try {
    // Write point
    const p = Point.measurement('stat')
      .setTag('unit', 'temperature')
      .setFloatField('avg', 24.5)
      .setFloatField('max', 45.0)
      .setTimestamp(new Date())
    await client.write(p, database)

    // Write point as template with anonymous fields object
    const pointTemplate = Object.freeze(
      Point.measurement('stat').setTag('unit', 'temperature')
    )

    const sensorData = {
      avg: 28,
      max: 40.3,
    }
    const p2 = pointTemplate
      .copy()
      .setFields(sensorData)
      .setTimestamp(new Date())

    await client.write(p2, database)

    // Or write directly line protocol
    const lp = `stat,unit=temperature avg=20.5,max=43.0`
    await client.write(lp, database)

    // Prepare flightsql query
    const query = `
      SELECT *
      FROM "stat"
      WHERE
      time >= now() - interval '5 minute'
      AND
      "unit" IN ('temperature')
    `
    const queryType = 'sql'

    // Execute query
    const queryResult = client.query(query, database, queryType)

    for await (const row of queryResult) {
      console.log(`avg is ${row.avg}`)
      console.log(`max is ${row.max}`)
    }

    // Execute query again as points
    const queryPointsResult = client.queryPoints(query, database, queryType)

    for await (const row of queryPointsResult) {
      console.log(`avg is ${row.getField('avg', 'float')}`)
      console.log(`max is ${row.getField('max', 'float')}`)
    }
  } catch (err) {
    console.error(err)
  } finally {
    await client.close()
  }
}

main()

```

**Comment by karel-rehor** [comment]
Yes, importing https instead of http and using the https agent fixes the issue.  Closing.
