### ISSUE TITLE
query transport: fails to trim white space from environment variables before they are used

### ISSUE THREAD

**Issue by karel-rehor** [InfluxCommunity/influxdb3-js#194]
### Specifications

* Client Version: 0.4.0
* InfluxDB Version: Influxdb3
* Platform: IOX 

### Code sample to reproduce problem

When setting up environment variables add a trailing white space character - maybe caused by a fat thumb. 

```bash

export INFLUX_HOST="https://us-east-1-1.aws.cloud2.influxdata.com "

```

and then instantiate the client with a constructor that depends on the environment variable.

```
...
let client = new InfluxDBClient();
...
```

Note trailing or leading white space can also occur in runner config settings in an IDE, which is where I first came across this issue.

### Expected behavior

Expected for the client to connect and write data and then query the response.  Unnecessary white space should be detected and trimmed from the variable value at some step of its use, if white space has no special meaning, or is even nonconformant with the protocol or use case. 

It seems this is being done for the write transport. All writes worked OK.  

### Actual behavior

However with the query transport this leads to a DNS lookup exception by gRPC. 

```
RpcError: Name resolution failed for target dns:us-east-1-1.aws.cloud2.influxdata.com :443
    at ClientReadableStreamImpl.<anonymous> (node_modules/@protobuf-ts/grpc-transport/build/commonjs/grpc-transport.js:85:52)
    at ClientReadableStreamImpl.emit (node:events:519:28)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client.js:357:28)
    at Object.onReceiveStatus (node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /home/karl/bonitoo/qa/testing/explore/influxdb3-client-tests/nodejs-client/js/yarn/node_modules/@grpc/grpc-js/build/src/resolving-call.js:99:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)
```

**Comment by karel-rehor** [comment]
verified fix in #221 works
