### ISSUE TITLE
Unable to read data from influxdb3

### ISSUE THREAD

**Issue by alexander-gulakov** [InfluxCommunity/influxdb3-js#363]
### Please direct all support questions to slack or the forums. Thank you.

**Actual Behavior**
@influxdata/influxdb3-client
client.query and client.queryPoints operations return error

```
RpcError: Database '0c9b613a389c4d84_a33de0bd22fec498' not found
    at ClientReadableStreamImpl.<anonymous> (pathto\node_modules\@protobuf-ts\grpc-transport\build\commonjs\grpc-transport.js:85:52)
    at ClientReadableStreamImpl.emit (node:events:390:28)
    at Object.onReceiveStatus (pathto\node_modules\@grpc\grpc-js\build\src\client.js:359:28)
RpcError: Database '0c9b613a389c4d84_a33de0bd22fec498' not found
    at ClientReadableStreamImpl.<anonymous> (pathto\node_modules\@protobuf-ts\grpc-transport\build\commonjs\grpc-transport.js:85:52)
    at ClientReadableStreamImpl.emit (node:events:390:28)
    at Object.onReceiveStatus (pathto\node_modules\@grpc\grpc-js\build\src\client.js:359:28)
s\grpc-transport.js:85:52)
    at ClientReadableStreamImpl.emit (node:events:390:28)
    at Object.onReceiveStatus (pathto\node_modules\@grpc\grpc-js\build\src\client.js:359:28)
    at Object.onReceiveStatus (pathto\node_modules\@grpc\grpc-js\build\src\client.js:359:28)
    at Object.onReceiveStatus (pathto\node_modules\@grpc\grpc-js\build\src\client-interceptors.js:323:181)    at pathto\node_modules\@grpc\grpc-js\build\src\resolving-call.js:129:78
    at processTicksAndRejections (node:internal/process/task_queues:78:11) {
  code: 'NOT_FOUND',
  meta: {},
  methodName: 'DoGet',
  serviceName: 'arrow.flight.protocol.FlightService'
}
```

**Expected Behavior**
client.query and client.queryPoint should return result instead of error
**More Context:**
- Storage engine is TSM (version 2)
- Write is ok. But with read I enforced above mentioned error 
- also tried with this example - https://github.com/InfluxCommunity/influxdb3-js/blob/5cad6a9e14c36c753f78d19b9d655418d177a930/examples/basic/src/index.ts
Changed there only credentials and run. 
The data was written to db successfully, but on reading still have the same error

**Comment by bednar** [comment]
Hi @alexander-gulakov,

Thank you for choosing our client for your data management needs.

I noticed your inquiry about the compatibility of the `influxdb3-js` client. This client is specifically designed to work with InfluxDB 3, which includes both InfluxDB Serverless and Dedicated versions.  

The TSM engine is not supported.

For more detailed information about what InfluxDB 3 offers and how you can leverage its capabilities, please visit these resources:
- [InfluxDB Overview](https://www.influxdata.com/products/influxdb-overview/)
- [InfluxDB Cloud Serverless](https://www.influxdata.com/products/influxdb-cloud/serverless/)

These pages will provide you with a comprehensive understanding of the features, benefits, and how to get started with InfluxDB Serverless or Dedicated to ensure optimal use of our client.

Should you have any further questions or need assistance with setup and configuration, please don't hesitate to reach out.

Best Regards
